[features]
seeds = true
skip-lint = false

[programs.localnet]
crowdsale_vesting = "DWpR44f2YDsQR1MZeucD1wrs1Toe4TbWJrZeM2PMSapm"

[programs.devnet]
crowdsale_vesting = "DWpR44f2YDsQR1MZeucD1wrs1Toe4TbWJrZeM2PMSapm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "yarn run ts-node app/init.ts"
init5min = "yarn run ts-node app/init_5min.ts"
initDevPublic = "yarn run ts-node app/init_devnet_public.ts"
initVestingCommunity = "yarn run ts-node app/init_vesting_community.ts"
